// Shared PDF generation utility for Plan Well.
// Imported dynamically so the heavy jsPDF bundle is only loaded on button click.

function fmt(n) {
  if (typeof n !== 'number') return String(n)
  return Number.isInteger(n) ? String(n) : String(parseFloat(n.toFixed(1)))
}

function devLabel(val) {
  return val > 0 ? `+${fmt(val)}` : `${fmt(val)}`
}

/**
 * Generates and downloads a PDF of a Plan Well 7-day meal plan.
 *
 * @param {object} plan  - The full plan object: { inputs, nutritionTargets, weeklyPlan, weeklySummary }
 * @param {object|null} foods - Food database map (name → macros). If null, the food reference
 *                              table is omitted (e.g. when downloading a saved plan).
 */
export async function generateMealPlanPDF(plan, foods) {
  // Dynamic imports — keeps the bundle small; only loaded client-side on demand.
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const { inputs, nutritionTargets, weeklyPlan, weeklySummary } = plan

  const dietLabel = {
    vegetarian: 'Vegetarian',
    'vegetarian+egg': 'Vegetarian + Egg',
    'non-vegetarian': 'Non-Vegetarian',
  }[inputs.dietType] || inputs.dietType

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth  = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  const contentWidth = pageWidth - margin * 2

  // ── Colour palette (Printer-friendly, professional nutrition layout) ──────────
  const C = {
    darkGreen:   [23,  53,  37],      // Primary Brand colour
    sageGreen:   [166, 192, 174],     // Accent borders
    white:       [255, 255, 255],
    lightGray:   [248, 250, 249],     // Card backgrounds
    darkText:    [40,  44,  42],      // Primary text
    softText:    [105, 115, 110],     // Subheadings / Hint labels
    rowAlt:      [250, 252, 250],     // Alternating table rows
    totalsRow:   [240, 245, 242],     // Summary card background
    warningBg:   [255, 253, 245],     // Alert box background
    warningText: [120, 85,   15],     // Alert box text
    success:     [30,  115,  60],     // Positive deviation / status
  }

  let y = 0

  // ── Helpers ─────────────────────────────────────────────────────────────────

  /** Check whether we need a new page before adding non-table content. */
  function checkPageBreak(needed = 20) {
    if (y + needed > pageHeight - 20) {
      doc.addPage()
      y = margin + 5
    }
  }

  /** Print page numbers and footer line on every page. */
  function addFooters() {
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(7.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.softText)
      doc.text('Generated by Plan Well • Personalized Indian Nutrition Planner', margin, pageHeight - 8)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 8, { align: 'right' })
      doc.setDrawColor(220, 225, 221)
      doc.setLineWidth(0.2)
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12)
    }
  }

  // ── PAGE 1: Premium Header + Details + Targets + Weekly Summary ─────────────────────

  // Top Accent Line
  doc.setFillColor(...C.darkGreen)
  doc.rect(margin, 10, contentWidth, 1.5, 'F')

  // Header Title
  doc.setTextColor(...C.darkGreen)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Plan Well', margin, 22)

  // Subtitle
  doc.setTextColor(...C.darkText)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('PERSONALIZED NUTRITION REPORT', margin, 27)

  // Date
  const today = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  doc.setFontSize(8.5)
  doc.setTextColor(...C.softText)
  doc.text(`Report Date: ${today}`, pageWidth - margin, 22, { align: 'right' })

  // Thin separator under header
  doc.setDrawColor(220, 225, 221)
  doc.setLineWidth(0.3)
  doc.line(margin, 32, pageWidth - margin, 32)

  y = 40

  // ── User details card ────────────────────────────────────────────────────────
  doc.setFillColor(...C.lightGray)
  doc.setDrawColor(...C.sageGreen)
  doc.setLineWidth(0.3)
  doc.roundedRect(margin, y, contentWidth, 24, 2, 2, 'FD')

  const details = [
    { label: 'Current Weight', val: `${inputs.weightKg} kg` },
    { label: 'Target Weight',  val: inputs.targetWeight ? `${inputs.targetWeight} kg` : '—' },
    { label: 'Daily Calories',  val: `${fmt(nutritionTargets.calories)} kcal` },
    { label: 'Diet Preference', val: dietLabel },
    { label: 'Meals Per Day',  val: `${inputs.mealsPerDay}` },
  ]
  const cardColW = contentWidth / 5

  details.forEach((det, i) => {
    const xCenter = margin + i * cardColW + cardColW / 2
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...C.softText)
    doc.text(det.label, xCenter, y + 8, { align: 'center' })
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...C.darkText)
    doc.text(det.val, xCenter, y + 15, { align: 'center' })

    if (i < 4) {
      doc.setDrawColor(220, 225, 221)
      doc.line(margin + (i + 1) * cardColW, y + 5, margin + (i + 1) * cardColW, y + 19)
    }
  })
  y += 34

  // ── Daily nutrition targets ──────────────────────────────────────────────────
  checkPageBreak(32)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.darkText)
  doc.text('Daily Nutrition Targets', margin, y)
  y += 4

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Calories', 'Protein', 'Carbohydrates', 'Fat', 'Fibre']],
    body: [[
      `${fmt(nutritionTargets.calories)} kcal`,
      `${fmt(nutritionTargets.protein)} g`,
      `${fmt(nutritionTargets.carbs)} g`,
      `${fmt(nutritionTargets.fat)} g`,
      `${fmt(nutritionTargets.fibre)} g`,
    ]],
    headStyles: { fillColor: C.darkGreen, textColor: C.white, fontStyle: 'bold', fontSize: 8.5, halign: 'center' },
    bodyStyles: { fontSize: 8.5, textColor: C.darkText, halign: 'center' },
    tableLineColor: [220, 225, 221],
    tableLineWidth: 0.15,
    theme: 'grid',
  })
  y = doc.lastAutoTable.finalY + 10

  // ── Weekly Nutrition Summary (Premium Boarded Section) ───────────────────────
  checkPageBreak(50)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.darkText)
  doc.text('Weekly Nutrition Summary (Averages)', margin, y)
  y += 4

  // Main Bordered Box
  doc.setDrawColor(...C.sageGreen)
  doc.setLineWidth(0.3)
  doc.setFillColor(...C.lightGray)
  doc.roundedRect(margin, y, contentWidth, 36, 2, 2, 'FD')

  const metrics = [
    { label: 'Average Calories', target: `${fmt(nutritionTargets.calories)} kcal`, achieved: `${fmt(weeklySummary.avgDailyAchieved.calories)} kcal`, dev: weeklySummary.avgDailyDeviation.calories, key: 'calories' },
    { label: 'Average Protein',  target: `${fmt(nutritionTargets.protein)} g`,    achieved: `${fmt(weeklySummary.avgDailyAchieved.protein)} g`,    dev: weeklySummary.avgDailyDeviation.protein,  key: 'protein' },
    { label: 'Average Carbs',    target: `${fmt(nutritionTargets.carbs)} g`,      achieved: `${fmt(weeklySummary.avgDailyAchieved.carbs)} g`,      dev: weeklySummary.avgDailyDeviation.carbs,    key: 'carbs' },
    { label: 'Average Fat',      target: `${fmt(nutritionTargets.fat)} g`,        achieved: `${fmt(weeklySummary.avgDailyAchieved.fat)} g`,        dev: weeklySummary.avgDailyDeviation.fat,      key: 'fat' },
    { label: 'Average Fibre',    target: `${fmt(nutritionTargets.fibre)} g`,      achieved: `${fmt(weeklySummary.avgDailyAchieved.fibre)} g`,      dev: weeklySummary.avgDailyDeviation.fibre,    key: 'fibre' },
  ]
  const metricColW = contentWidth / 5

  metrics.forEach((m, i) => {
    const xCenter = margin + i * metricColW + metricColW / 2
    
    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...C.softText)
    doc.text(m.label, xCenter, y + 8, { align: 'center' })
    
    // Achieved
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10.5)
    doc.setTextColor(...C.darkGreen)
    doc.text(m.achieved, xCenter, y + 16, { align: 'center' })
    
    // Target
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...C.softText)
    doc.text(`Target: ${m.target}`, xCenter, y + 23, { align: 'center' })
    
    // Deviation Colour Coding
    const devVal = m.dev
    const tol = m.key === 'calories' ? 50 : m.key === 'carbs' ? 10 : 5
    let devColor = C.success
    if (Math.abs(devVal) > tol) {
      devColor = devVal > 0 ? [180, 100, 10] : [50, 100, 150]
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(...devColor)
    doc.text(`Dev: ${devLabel(devVal)}`, xCenter, y + 29, { align: 'center' })

    if (i < 4) {
      doc.setDrawColor(220, 225, 221)
      doc.line(margin + (i + 1) * metricColW, y + 5, margin + (i + 1) * metricColW, y + 31)
    }
  })
  y += 46

  // ── PAGES 2+: 7-Day Meal Plan ────────────────────────────────────────────────
  doc.addPage()
  y = margin + 5

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.darkText)
  doc.text('7-Day Meal Plan Schedule', margin, y)
  doc.setFillColor(...C.sageGreen)
  doc.rect(margin, y + 2.5, contentWidth, 0.5, 'F')
  y += 9

  weeklyPlan.forEach((day) => {
    checkPageBreak(25)

    // Day Header Card
    doc.setFillColor(...C.lightGray)
    doc.setDrawColor(...C.sageGreen)
    doc.setLineWidth(0.3)
    doc.roundedRect(margin, y, contentWidth, 10, 1.5, 1.5, 'FD')

    doc.setTextColor(...C.darkGreen)
    doc.setFontSize(10.5)
    doc.setFont('helvetica', 'bold')
    const dayTitle = day.dayNote ? `Day ${day.day}  —  ${day.dayNote}` : `Day ${day.day}`
    doc.text(dayTitle, margin + 4, y + 6.5)
    y += 14

    day.meals.forEach((meal) => {
      checkPageBreak(36)

      // Meal Heading (Larger & cleaner spacing)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.darkGreen)
      doc.text(meal.meal, margin + 2, y)
      y += 4.5

      // Food items table
      const foodRows = meal.items.map(item => [
        item.name,
        `${item.qty}${item.unit}`,
        `${fmt(item.macros.calories)} kcal`,
        `${fmt(item.macros.protein)} g`,
        `${fmt(item.macros.carbs)} g`,
        `${fmt(item.macros.fat)} g`,
        `${fmt(item.macros.fibre)} g`,
      ])

      autoTable(doc, {
        startY: y,
        margin: { left: margin + 2, right: margin },
        head: [['Food Item', 'Qty', 'Calories', 'Protein', 'Carbs', 'Fat', 'Fibre']],
        body: foodRows,
        headStyles: {
          fillColor: C.lightGray,
          textColor: C.darkText,
          fontStyle: 'bold',
          fontSize: 8,
          lineColor: [220, 225, 221],
          lineWidth: 0.15,
        },
        bodyStyles: { fontSize: 8, textColor: C.darkText },
        alternateRowStyles: { fillColor: C.rowAlt },
        tableLineColor: [220, 225, 221],
        tableLineWidth: 0.15,
        theme: 'grid',
        columnStyles: { 
          0: { cellWidth: 62 },
          1: { halign: 'center' },
          2: { halign: 'right' },
          3: { halign: 'right' },
          4: { halign: 'right' },
          5: { halign: 'right' },
          6: { halign: 'right' }
        },
      })

      y = doc.lastAutoTable.finalY + 3.5

      // Meal Nutrition Summary Card
      checkPageBreak(13)
      doc.setFillColor(252, 252, 252)
      doc.setDrawColor(215, 225, 218)
      doc.setLineWidth(0.25)
      doc.roundedRect(margin + 2, y, contentWidth - 2, 10, 1.2, 1.2, 'FD')

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(...C.darkGreen)
      doc.text('Meal Nutrition Summary:', margin + 5, y + 6.5)

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7.5)
      doc.setTextColor(...C.darkText)
      doc.text(
        `Calories: ${fmt(meal.mealTotals.calories)} kcal   |   Protein: ${fmt(meal.mealTotals.protein)}g   |   Carbs: ${fmt(meal.mealTotals.carbs)}g   |   Fat: ${fmt(meal.mealTotals.fat)}g   |   Fibre: ${fmt(meal.mealTotals.fibre)}g`,
        margin + 42,
        y + 6.5
      )
      y += 15
    })

    // Daily Nutrition Summary Box
    checkPageBreak(16)
    const ds = day.dailySummary
    doc.setFillColor(...C.totalsRow)
    doc.setDrawColor(...C.sageGreen)
    doc.setLineWidth(0.3)
    doc.roundedRect(margin, y, contentWidth, 12, 1.5, 1.5, 'FD')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(...C.darkGreen)
    doc.text('Daily Nutrition Summary', margin + 4, y + 7.5)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...C.darkText)
    doc.text(
      `Calories: ${fmt(ds.achieved.calories)} kcal   |   Protein: ${fmt(ds.achieved.protein)}g   |   Carbs: ${fmt(ds.achieved.carbs)}g   |   Fat: ${fmt(ds.achieved.fat)}g   |   Fibre: ${fmt(ds.achieved.fibre)}g`,
      margin + 46,
      y + 7.5
    )
    y += 20
  })

  // ── Food Reference Table (only when foods DB is available) ────────────────────
  if (foods) {
    doc.addPage()
    y = margin + 5

    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.darkText)
    doc.text('Food Reference Index', margin, y)
    doc.setFillColor(...C.sageGreen)
    doc.rect(margin, y + 2.5, contentWidth, 0.5, 'F')

    y += 8
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.softText)
    doc.text('All nutritional values used in your plan, per 100g or 100ml.', margin, y)
    y += 5

    const usedFoods = new Set()
    weeklyPlan.forEach(day =>
      day.meals.forEach(meal =>
        meal.items.forEach(item => usedFoods.add(item.name))
      )
    )

    const refRows = [...usedFoods].sort().map(name => {
      const f = foods[name]
      if (!f) return null
      const unit = f.serving.includes('ml') ? '100ml' : '100g'
      return [
        name, unit,
        `${fmt(f.calories)} kcal`,
        `${fmt(f.protein)} g`,
        `${fmt(f.carbs)} g`,
        `${fmt(f.fat)} g`,
        `${fmt(f.fibre)} g`,
      ]
    }).filter(Boolean)

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Food Name', 'Per', 'Calories', 'Protein', 'Carbs', 'Fat', 'Fibre']],
      body: refRows,
      headStyles: { fillColor: C.darkGreen, textColor: C.white, fontStyle: 'bold', fontSize: 8.5 },
      bodyStyles: { fontSize: 8, textColor: C.darkText },
      alternateRowStyles: { fillColor: C.rowAlt },
      tableLineColor: [220, 225, 221],
      tableLineWidth: 0.15,
      theme: 'grid',
      columnStyles: { 
        0: { cellWidth: 62 },
        1: { halign: 'center' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'right' },
        6: { halign: 'right' }
      },
    })

    y = doc.lastAutoTable.finalY + 12
  }

  // ── Notes & Disclaimer ────────────────────────────────────────────────────────
  checkPageBreak(50)

  // Recommendation warning card
  doc.setFillColor(...C.warningBg)
  doc.setDrawColor(...C.warningText)
  doc.setLineWidth(0.3)
  doc.roundedRect(margin, y, contentWidth, 22, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.warningText)
  doc.text('Weight Update Recommendation', margin + 5, y + 7)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...C.darkText)
  const noteLines = doc.splitTextToSize(
    'If your weight has reduced by approximately 2 kg or more since starting this plan, re-generate with your updated weight for better accuracy.',
    contentWidth - 10
  )
  doc.text(noteLines, margin + 5, y + 14)
  y += 28

  // Disclaimer text
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(...C.softText)
  const disclaimerLines = doc.splitTextToSize(
    'Disclaimer: Plan Well is intended for educational and planning purposes only. It does not provide medical advice. Users with medical conditions or specific dietary requirements should consult a qualified healthcare professional or nutritionist before making dietary changes.',
    contentWidth
  )
  doc.text(disclaimerLines, margin, y)

  // ── Add footers to all pages, then save ──────────────────────────────────────
  addFooters()

  const dateStr = new Date().toISOString().split('T')[0]
  doc.save(`PlanWell-MealPlan-${dateStr}.pdf`)
}
